# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose port 7767 to outside the container
EXPOSE 7767

# Define environment variable
ENV FLASK_APP gemAPI.py

# Run gemAPI.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=7767"]
